baseURL = 'https://tatk.network/'
languageCode = 'en-gb'
title = 'TATK DN42 Network'

theme = "bootstrap"
relativeURLS = true
enableRobotsTXT = true
enableGitInfo = true

[menus]
  [[menus.main]]
  name = "Looking Glass"
  weight = 900
  url = "https://lg.tatk.network"
  [menus.main.params]
      target = "_blank"

  [[menus.main]]
  name = "Status Page"
  weight = 901
  url = "https://status.tatk.network"
  [menus.main.params]
      target = "_blank"